import { Inter } from 'next/font/google';
import { Metadata } from 'next';
import { dir } from 'i18next';
import { Suspense } from 'react';
import QueryClientProvider from '@/queries/QueryClientProvider';
import { locales } from '@/i18n';
import { LanguageSwitcher } from '@/components/shared/LanguageSwitcher';
import Providers from '@/contexts/Providers';

export async function generateStaticParams() {
  return locales.map((lng) => ({ lng }));
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: '%s | Acme',
    absolute: 'Acme'
  },
  description: 'Generated by create next app'
};

export default function RootLayout({
  children,
  params: { lng }
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <QueryClientProvider>
          <Providers lng={lng}>
            <Suspense fallback={<div>loading..</div>}>
              <LanguageSwitcher />
            </Suspense>
            {children}
          </Providers>
        </QueryClientProvider>
      </body>
    </html>
  );
}
